export const PROTOCOL_CLEANUP = `\
# Cleanup Protocol (Generalized)

**version:** 1.1
**purpose:** Safe, repeatable cleanup of build artifacts, caches, test outputs, and temporary files — restoring a clean, reproducible workspace.
**safety:** Always run dry-run first. Nothing is deleted without review.
**output:** List of removed items + clean state confirmation.

## Core Principle
Only delete things that are safely regeneratable. Make it trivial to extend with your own project-specific targets.

## Standard Safe Targets

Use this table as your starting point (narrow and scannable):

| CLN-ID | Target Pattern(s)                  | Why Safe to Delete                          | How (generalized)                     |
|--------|------------------------------------|---------------------------------------------|---------------------------------------|
| CLN-001 | \`dist/\`, \`build/\`, \`out/\`   | Fully regenerated by your build step       | \`rm -rf dist/ build/ out/\`         |
| CLN-002 | Coverage / test reports            | Regenerated by test runs                   | \`rm -rf coverage/ .nyc_output/\`    |
| CLN-003 | Incremental caches                 | Safe to delete (e.g. \`.tsbuildinfo\`)     | \`rm -f *.tsbuildinfo\`              |
| CLN-004 | Temp test / playwright / cypress dirs | Created by manual or CI test runs         | \`rm -rf /tmp/test-* /tmp/playwright-*\` |
| CLN-005 | Pack artifacts                     | Local \`npm pack\` / equivalent output     | \`rm -f *.tgz *.tar.gz\`             |
| CLN-006 | OS / editor junk                   | Auto-generated (\`.DS_Store\`, \*.swp, etc.) | See commands below                    |

## Recommended Dry-Run + Execute Process

1. **Always dry-run first** (list before deleting)
2. Review the output carefully
3. Execute only what you are comfortable with
4. Verify with \`git status\` and \`git diff --stat\`

Example dry-run command (customize for your stack):

\`\`\`bash
echo "=== DRY RUN ==="
echo "Build artifacts:" && ls -la dist/ build/ out/ 2>/dev/null || echo "  (none)"
echo "Coverage:" && ls -la coverage/ 2>/dev/null || echo "  (none)"
echo "Caches:" && ls -la *.tsbuildinfo 2>/dev/null || echo "  (none)"
echo "Temp dirs:" && ls -la /tmp/test-* /tmp/playwright-* 2>/dev/null || echo "  (none)"
echo "Pack artifacts:" && ls -la *.tgz 2>/dev/null || echo "  (none)"
find . -name ".DS_Store" -not -path "*/.git/*" | head -20
\`\`\`

## Add Your Project-Specific Safe Targets

Copy the table header above and add rows using CLN-1xx IDs.

**Good candidates for your project:**
- Framework outputs (e.g. \`.next/\`, \`target/\`, \`*.pyc\`, \`node_modules/.cache\`)
- Generated documentation or storybook folders
- Local database / dev data you are comfortable resetting
- Custom temporary directories from your scripts or dev servers

**Your custom targets:**

| CLN-ID | Target Pattern(s) | Why Safe to Delete | How |
|--------|-------------------|--------------------|-----|
| CLN-100 | (your target)     | (why it's safe)    | (command) |

**Never delete these** (add your own rules here):
- \`node_modules/\` (use \`npm ci\` deliberately)
- Source code
- \`wiki/\`, \`docs/\`, \`protocols/\` (knowledge artifacts)
- Anything tracked by git
- User configuration that may contain uncommitted state

## Success Criteria

- [ ] Dry run reviewed before any deletion
- [ ] Workspace returns to clean \`git status\`
- [ ] No important uncommitted work was lost

---

*Generalized cleanup protocol. Extend the table above with targets that are safe in your environment.*

## Changelog

| Version | Date       | Change |
|---------|------------|--------|
| 1.1     | 2026-05-27 | Deepened with "Why Safe" rationales and extension table |
`;

